import type { Wisdom } from "./types";

/**
 * パブリックドメイン／広く知られた格言・逸話の日本語意訳・要約。
 * 原文の厳密な翻訳ではなく、読みやすさ優先の意訳を含む。
 */
export const wisdoms: Wisdom[] = [
  {
    id: "w001",
    kind: "quote",
    text: "人を動かす唯一の方法は、相手が自ら動きたいと思うようにすることだ。",
    author: "デール・カーネギー",
    role: "作家・教育者",
    category: "leadership",
  },
  {
    id: "w002",
    kind: "quote",
    text: "リーダーとは、道を示し、自ら歩き、そして人を信じて委ねる人である。",
    author: "ジャック・ウェルチ",
    role: "元GE CEO",
    category: "leadership",
  },
  {
    id: "w003",
    kind: "quote",
    text: "優れたリーダーは、部下の手柄を自分のものにしない。失敗は自分の責任として引き受ける。",
    author: "孫子",
    role: "兵法家",
    category: "leadership",
    source: "『孫子』の思想に基づく要約",
  },
  {
    id: "w004",
    kind: "quote",
    text: "マネジメントとは、正しいことを行うこと。リーダーシップとは、何が正しいかを決めることだ。",
    author: "ピーター・ドラッカー",
    role: "経営学者",
    category: "leadership",
  },
  {
    id: "w005",
    kind: "anecdote",
    text: "松下幸之助は、若い社員の提案を最後まで聞き、「あなたがそう言うなら、やってみよう」と答えたという。権限より信頼が、人を動かすと考えていた。",
    author: "松下幸之助",
    role: "パナソニック創業者",
    category: "leadership",
  },
  {
    id: "w006",
    kind: "quote",
    text: "イノベーションとは、顧客の言葉に従うことではない。顧客がまだ知らない欲求を見つけることだ。",
    author: "スティーブ・ジョブズ",
    role: "Apple共同創業者",
    category: "innovation",
  },
  {
    id: "w007",
    kind: "quote",
    text: "既存のものを少しよくするだけでは足りない。根本から作り直す覚悟が必要だ。",
    author: "イーロン・マスク",
    role: "起業家",
    category: "innovation",
  },
  {
    id: "w008",
    kind: "quote",
    text: "創造性とは、既存の要素を新しい組み合わせでつなぐことだ。",
    author: "アインシュタイン",
    role: "物理学者",
    category: "innovation",
  },
  {
    id: "w009",
    kind: "anecdote",
    text: "本田宗一郎は、失敗した試作車を前に怒らず、「失敗は成功の母だ。次をやれ」と技術者を励ましたという。挑戦を罰しない文化が、技術革新を支えた。",
    author: "本田宗一郎",
    role: "ホンダ創業者",
    category: "innovation",
  },
  {
    id: "w010",
    kind: "quote",
    text: "破壊的イノベーションは、最初は小さく、見過ごされやすい場所から始まる。",
    author: "クレイトン・クリステンセン",
    role: "経営学者",
    category: "innovation",
  },
  {
    id: "w011",
    kind: "quote",
    text: "天才とは、1%のひらめきと99%の努力である。",
    author: "トーマス・エジソン",
    role: "発明家",
    category: "perseverance",
  },
  {
    id: "w012",
    kind: "quote",
    text: "敗北は、あきらめたときにだけ確定する。",
    author: "孔子",
    role: "思想家",
    category: "perseverance",
  },
  {
    id: "w013",
    kind: "quote",
    text: "成功するまで続ければ、失敗ではない。",
    author: "ジョージ・パットン",
    role: "軍人",
    category: "perseverance",
  },
  {
    id: "w014",
    kind: "anecdote",
    text: "J.K.ローリングは、ハリー・ポッターの原稿を複数の出版社に断られた。それでも書き続け、世界的ベストセラーとなった。拒絶は終わりではなく、次の扉の前だった。",
    author: "J.K.ローリング",
    role: "作家",
    category: "perseverance",
  },
  {
    id: "w015",
    kind: "quote",
    text: "山は、登り続ける者の前にだけ道を開く。",
    author: "宮本武蔵",
    role: "剣豪",
    category: "perseverance",
    source: "『五輪書』の精神に基づく意訳",
  },
  {
    id: "w016",
    kind: "quote",
    text: "知ることは愛することの始まりであり、愛することは理解することの始まりである。",
    author: "ティッヒ・ナット・ハン",
    role: "僧侶・平和活動家",
    category: "wisdom",
  },
  {
    id: "w017",
    kind: "quote",
    text: "我思う、ゆえに我あり。",
    author: "デカルト",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w018",
    kind: "quote",
    text: "物事は、あなたがどう見るかによって変わる。見方を変えれば、世界も変わる。",
    author: "マルクス・アウレリウス",
    role: "ローマ皇帝・ストア派哲学者",
    category: "wisdom",
  },
  {
    id: "w019",
    kind: "quote",
    text: "無知の知——自分が知らないことを知る者こそ、賢い。",
    author: "ソクラテス",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w020",
    kind: "anecdote",
    text: "老子は、強さとは水のように柔らかいものだと説いた。岩を削るのも、低い場所へ流れるのも、争わずに道を見つけるのも水である、と。",
    author: "老子",
    role: "思想家",
    category: "wisdom",
  },
  {
    id: "w021",
    kind: "quote",
    text: "企業の目的は、顧客の創造である。",
    author: "ピーター・ドラッカー",
    role: "経営学者",
    category: "business",
  },
  {
    id: "w022",
    kind: "quote",
    text: "価格は忘れられても、品質は長く残る。",
    author: "グルーチョ・マルクス（通説）／品質経営の格言",
    role: "経営の諺",
    category: "business",
  },
  {
    id: "w023",
    kind: "quote",
    text: "あなたの利益は、顧客が払う対価ではなく、顧客が得る価値にある。",
    author: "ジェフ・ベゾス",
    role: "Amazon創業者",
    category: "business",
  },
  {
    id: "w024",
    kind: "anecdote",
    text: "稲盛和夫は、京セラ創業時から「値決めは経営である」と説いた。安売りでも暴利でもなく、お客様も会社も納得できる一点を見つけることが、経営者の仕事だと。",
    author: "稲盛和夫",
    role: "京セラ創業者",
    category: "business",
  },
  {
    id: "w025",
    kind: "quote",
    text: "小さく始め、早く学び、大きく育てよ。",
    author: "エリック・リース",
    role: "起業家・著者",
    category: "business",
  },
  {
    id: "w026",
    kind: "quote",
    text: "勇気とは、恐れがないことではない。恐れがあっても前へ進むことだ。",
    author: "ネルソン・マンデラ",
    role: "政治家・人権活動家",
    category: "courage",
  },
  {
    id: "w027",
    kind: "quote",
    text: "船は港にいれば安全だ。だが、それは船の目的ではない。",
    author: "ジョン・A・シェッド",
    role: "著述家",
    category: "courage",
  },
  {
    id: "w028",
    kind: "quote",
    text: "人生で最も大きな危険は、危険を冒さないことだ。",
    author: "マーク・ザッカーバーグ",
    role: "Meta創業者",
    category: "courage",
  },
  {
    id: "w029",
    kind: "anecdote",
    text: "ヘレン・ケラーは視覚と聴覚を失いながらも、世界に向けて語り続けた。「世界で最も美しいものは、目で見たり触れたりできない。心で感じなければならない」と。",
    author: "ヘレン・ケラー",
    role: "著述家・社会活動家",
    category: "courage",
  },
  {
    id: "w030",
    kind: "quote",
    text: "困難の中に、機会がある。",
    author: "アインシュタイン",
    role: "物理学者",
    category: "courage",
  },
  {
    id: "w031",
    kind: "quote",
    text: "人生とは、自分が他の人のために何をしたかで測られる。",
    author: "アインシュタイン",
    role: "物理学者",
    category: "life",
  },
  {
    id: "w032",
    kind: "quote",
    text: "今日という日は、残りの人生の最初の日である。",
    author: "チャールズ・ディケンズ（通説）",
    role: "作家",
    category: "life",
  },
  {
    id: "w033",
    kind: "quote",
    text: "シンプルに生きよ。ただし、単純には考えるな。",
    author: "オリバー・ウェンデル・ホームズ",
    role: "法学者",
    category: "life",
  },
  {
    id: "w034",
    kind: "anecdote",
    text: "ガンディーは、簡素な生活と非暴力を貫いた。力でねじ伏せるのではなく、正しさで相手の良心に訴える——それが、彼の選んだ生き方だった。",
    author: "マハトマ・ガンディー",
    role: "独立運動指導者",
    category: "life",
  },
  {
    id: "w035",
    kind: "quote",
    text: "幸せは、向かう方向であって、場所ではない。",
    author: "シドニー・J・ハリス",
    role: "ジャーナリスト",
    category: "life",
  },
  {
    id: "w036",
    kind: "quote",
    text: "学びて思わざれば則ち罔し。思いて学ばざれば則ち殆し。",
    author: "孔子",
    role: "思想家",
    category: "learning",
    source: "『論語』",
  },
  {
    id: "w037",
    kind: "quote",
    text: "私は特別に才能があるわけではない。ただ、情熱的に好奇心を持つだけだ。",
    author: "アインシュタイン",
    role: "物理学者",
    category: "learning",
  },
  {
    id: "w038",
    kind: "quote",
    text: "読書は、すでに考えられたことを追体験する最も速い方法だ。",
    author: "チャーリー・マンガー",
    role: "投資家",
    category: "learning",
  },
  {
    id: "w039",
    kind: "anecdote",
    text: "福沢諭吉は、蘭学から英語へ、そして西洋の制度へと学び続けた。一つの知識に安住せず、時代が求める次の学びへ移る姿勢が、近代日本の精神を形づくった。",
    author: "福沢諭吉",
    role: "思想家・教育者",
    category: "learning",
  },
  {
    id: "w040",
    kind: "quote",
    text: "経験から学ぶ者は賢い。他人の経験から学ぶ者は、さらに賢い。",
    author: "オットー・フォン・ビスマルク",
    role: "政治家",
    category: "learning",
  },
  {
    id: "w041",
    kind: "quote",
    text: "ビジョンなきところに、実行も成果もない。",
    author: "ヘレン・ケラー",
    role: "著述家・社会活動家",
    category: "leadership",
  },
  {
    id: "w042",
    kind: "quote",
    text: "最も重要なことは、言うことではなく、行うことだ。",
    author: "ジョン・ウッドン",
    role: "バスケットボール指導者",
    category: "leadership",
  },
  {
    id: "w043",
    kind: "quote",
    text: "変化を恐れず、変化を自ら起こす側に回れ。",
    author: "ジャック・マー",
    role: "アリババ創業者",
    category: "innovation",
  },
  {
    id: "w044",
    kind: "quote",
    text: "最初から完璧を目指すな。まず動け。",
    author: "リード・ホフマン",
    role: "LinkedIn共同創業者",
    category: "innovation",
  },
  {
    id: "w045",
    kind: "quote",
    text: "落下しても、立ち上がる回数の方が多ければよい。",
    author: "孔子",
    role: "思想家",
    category: "perseverance",
  },
  {
    id: "w046",
    kind: "quote",
    text: "石の上にも三年。ただし、三年で諦めるな。十年を見据えよ。",
    author: "日本の諺（拡張）",
    role: "ことわざ",
    category: "perseverance",
  },
  {
    id: "w047",
    kind: "quote",
    text: "静かな心は、どんな嵐の中でも港になれる。",
    author: "エピクロス",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w048",
    kind: "quote",
    text: "測れるものは改善できる。測れないものは管理できない。",
    author: "ピーター・ドラッカー",
    role: "経営学者",
    category: "business",
  },
  {
    id: "w049",
    kind: "quote",
    text: "顧客に恋をし、競合に執着するな。",
    author: "ジェフ・ベゾス",
    role: "Amazon創業者",
    category: "business",
  },
  {
    id: "w050",
    kind: "quote",
    text: "安全な道を選ぶことが、いちばん危険なときがある。",
    author: "パウロ・コエーリョ",
    role: "作家",
    category: "courage",
  },
  {
    id: "w051",
    kind: "quote",
    text: "人生の意味は、与えられるものではなく、自らつくるものだ。",
    author: "ヴィクトール・フランクル",
    role: "精神科医・著者",
    category: "life",
  },
  {
    id: "w052",
    kind: "quote",
    text: "教育の目的は、知識を詰めることではなく、考える力を育てることだ。",
    author: "アインシュタイン",
    role: "物理学者",
    category: "learning",
  },
  {
    id: "w053",
    kind: "quote",
    text: "信頼は、言葉ではなく一貫した行動から生まれる。",
    author: "スティーブン・R・コヴィー",
    role: "著述家",
    category: "leadership",
  },
  {
    id: "w054",
    kind: "anecdote",
    text: "渋沢栄一は、利益と道徳は両立すると説き、『論語と算盤』にその思想を残した。事業の成功は、社会への貢献と切り離せない、というのが彼の経営観だった。",
    author: "渋沢栄一",
    role: "実業家",
    category: "business",
  },
  {
    id: "w055",
    kind: "quote",
    text: "アイデアは安い。実行がすべてだ。",
    author: "スティーブ・ジョブズ",
    role: "Apple共同創業者",
    category: "innovation",
  },
  {
    id: "w056",
    kind: "quote",
    text: "忍耐とは、待っているあいだに何をするかだ。",
    author: "ヘンリー・ロングフェロー",
    role: "詩人",
    category: "perseverance",
  },
  {
    id: "w057",
    kind: "quote",
    text: "自分を知ることは、すべての知恵の始まりである。",
    author: "アリストテレス",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w058",
    kind: "quote",
    text: "恐れは心の中にある。踏み出せば、恐れの半分は消える。",
    author: "セオドア・ルーズベルト",
    role: "アメリカ大統領",
    category: "courage",
  },
  {
    id: "w059",
    kind: "quote",
    text: "人生は短い。だからこそ、大切なことに時間を使え。",
    author: "セネカ",
    role: "哲学者",
    category: "life",
  },
  {
    id: "w060",
    kind: "quote",
    text: "学び続ける者だけが、変化する世界についていける。",
    author: "ピーター・ドラッカー",
    role: "経営学者",
    category: "learning",
  },
  {
    id: "w061",
    kind: "quote",
    text: "人を雇うときは、スキルより意志を見よ。スキルは教えられる。",
    author: "サイモン・シネック",
    role: "著述家",
    category: "leadership",
  },
  {
    id: "w062",
    kind: "quote",
    text: "明日の当たり前は、今日の非常識から生まれる。",
    author: "孫正義",
    role: "ソフトバンクグループ創業者",
    category: "innovation",
  },
  {
    id: "w063",
    kind: "anecdote",
    text: "ウォルト・ディズニーは破産を経験し、ミッキーマウスの構想も当初は相手にされなかった。それでも物語と夢を諦めず、やがて娯楽の帝国をつくった。",
    author: "ウォルト・ディズニー",
    role: "起業家・アニメーター",
    category: "perseverance",
  },
  {
    id: "w064",
    kind: "quote",
    text: "真実は、わかりやすい言葉の中にあることが多い。",
    author: "レオナルド・ダ・ヴィンチ",
    role: "芸術家・発明家",
    category: "wisdom",
  },
  {
    id: "w065",
    kind: "quote",
    text: "長期で考え、短期で実行せよ。",
    author: "ジェフ・ベゾス",
    role: "Amazon創業者",
    category: "business",
  },
  {
    id: "w066",
    kind: "quote",
    text: "勇気の反対は臆病ではない。適合することだ。",
    author: "ロロ・メイ",
    role: "心理学者",
    category: "courage",
  },
  {
    id: "w067",
    kind: "quote",
    text: "自分の人生の著者になれ。他人の脚注になるな。",
    author: "オリバー・ウェンデル・ホームズ",
    role: "法学者",
    category: "life",
  },
  {
    id: "w068",
    kind: "quote",
    text: "質問を変えると、見える世界が変わる。",
    author: "アインシュタイン",
    role: "物理学者",
    category: "learning",
  },
  {
    id: "w069",
    kind: "quote",
    text: "部下に仕事を任せるとは、結果を任せる覚悟を持つことだ。",
    author: "松下幸之助",
    role: "パナソニック創業者",
    category: "leadership",
  },
  {
    id: "w070",
    kind: "quote",
    text: "技術は手段だ。目的は、人の生活をよりよくすることにある。",
    author: "ビル・ゲイツ",
    role: "Microsoft共同創業者",
    category: "innovation",
  },
  {
    id: "w071",
    kind: "quote",
    text: "継続は力なり。ただし、改善なき継続は惰性なり。",
    author: "日本の諺（拡張）",
    role: "ことわざ",
    category: "perseverance",
  },
  {
    id: "w072",
    kind: "quote",
    text: "怒りは一時の狂気である。",
    author: "ホラティウス",
    role: "詩人",
    category: "wisdom",
  },
  {
    id: "w073",
    kind: "anecdote",
    text: "盛田昭夫は、ウォークマンの社内反対を押し切り発売した。市場調査に頼るより、「人々が音楽を持ち歩く世界」を信じた決断だった。",
    author: "盛田昭夫",
    role: "ソニー共同創業者",
    category: "business",
  },
  {
    id: "w074",
    kind: "quote",
    text: "最初の一歩が、いちばん勇気がいる。",
    author: "老子",
    role: "思想家",
    category: "courage",
  },
  {
    id: "w075",
    kind: "quote",
    text: "比較は、喜びを盗む泥棒だ。",
    author: "セオドア・ルーズベルト",
    role: "アメリカ大統領",
    category: "life",
  },
  {
    id: "w076",
    kind: "quote",
    text: "教えることは、二度学ぶことだ。",
    author: "ジョセフ・ジュベール",
    role: "随筆家",
    category: "learning",
  },
  {
    id: "w077",
    kind: "quote",
    text: "文化は戦略に勝る。どんな計画も、現場の空気に負ける。",
    author: "ピーター・ドラッカー",
    role: "経営学者",
    category: "leadership",
  },
  {
    id: "w078",
    kind: "quote",
    text: "未来は、予測するものではなく、つくるものだ。",
    author: "ピーター・ドラッカー",
    role: "経営学者",
    category: "innovation",
  },
  {
    id: "w079",
    kind: "quote",
    text: "成功の反対は失敗ではない。何もしないことだ。",
    author: "ロバート・シューラー",
    role: "牧師・著述家",
    category: "perseverance",
  },
  {
    id: "w080",
    kind: "quote",
    text: "知恵とは、何を無視すべきかを知ることだ。",
    author: "ウィリアム・ジェームズ",
    role: "心理学者・哲学者",
    category: "wisdom",
  },
  {
    id: "w081",
    kind: "quote",
    text: "情報革命でいちばん大事なのは、情報そのものではない。情報をどう使い、どんな事業をつくるかだ。",
    author: "孫正義",
    role: "ソフトバンクグループ創業者",
    category: "business",
  },
  {
    id: "w082",
    kind: "anecdote",
    text: "孫正義は「タイムマシン経営」を説いた。先進国で起きた変化を先に学び、自国市場へ持ち込んでスピードで勝つ——時間差を事業機会に変える発想だ。",
    author: "孫正義",
    role: "ソフトバンクグループ創業者",
    category: "business",
  },
  {
    id: "w083",
    kind: "quote",
    text: "ネットの時代は、スピードがすべてだ。迷っているあいだに、機会は消える。",
    author: "藤田晋",
    role: "サイバーエージェント創業者",
    category: "business",
  },
  {
    id: "w084",
    kind: "anecdote",
    text: "藤田晋は「若手が挑戦できる会社」を掲げ、新規事業を次々と任せてきた。失敗を許容する文化こそが、成長企業の燃料だと考えている。",
    author: "藤田晋",
    role: "サイバーエージェント創業者",
    category: "business",
  },
  {
    id: "w085",
    kind: "quote",
    text: "商売は、お客様の喜びを大きくすることから始まる。利益はその結果についてくる。",
    author: "松下幸之助",
    role: "パナソニック創業者",
    category: "business",
  },
  {
    id: "w086",
    kind: "quote",
    text: "水道哲学——良品を安く、豊富に供給し、人々の生活を豊かにすること。それが産業人の使命だ。",
    author: "松下幸之助",
    role: "パナソニック創業者",
    category: "business",
  },
  {
    id: "w087",
    kind: "quote",
    text: "技術は、人の役に立って初めて意味がある。売れるものより、使われるものをつくれ。",
    author: "本田宗一郎",
    role: "ホンダ創業者",
    category: "business",
  },
  {
    id: "w088",
    kind: "anecdote",
    text: "本田宗一郎は「技術で社会に貢献する」ことを事業の軸に据えた。レースでの挑戦も、量産車の品質向上も、同じものづくりの延長線上にあると考えていた。",
    author: "本田宗一郎",
    role: "ホンダ創業者",
    category: "business",
  },
  {
    id: "w089",
    kind: "quote",
    text: "好奇心と創造力があれば、技術は必ず人の生活を変える。",
    author: "井深大",
    role: "ソニー共同創業者",
    category: "business",
  },
  {
    id: "w090",
    kind: "anecdote",
    text: "井深大は創業時の「目的書」で、大企業ではできない自由な技術探求と、真面目な技術者集団の会社をつくることを掲げた。ソニーの原点は、利益より先に「やりたい技術」にあった。",
    author: "井深大",
    role: "ソニー共同創業者",
    category: "business",
  },
  {
    id: "w091",
    kind: "quote",
    text: "グローバルに考え、ローカルに行動せよ。世界共通の価値と、現地の感性の両方を持て。",
    author: "盛田昭夫",
    role: "ソニー共同創業者",
    category: "business",
  },
  {
    id: "w092",
    kind: "quote",
    text: "ブランドとは、お客様の頭の中にある約束だ。製品より長く残る資産である。",
    author: "盛田昭夫",
    role: "ソニー共同創業者",
    category: "business",
  },
  {
    id: "w093",
    kind: "quote",
    text: "事業が何であるかを決めるのは、経営者ではなく顧客である。",
    author: "ピーター・ドラッカー",
    role: "経営学者",
    category: "business",
  },
  {
    id: "w094",
    kind: "quote",
    text: "マーケティングの理想は、販売を不要にすることだ。顧客を深く理解すれば、商品は自ら売れる。",
    author: "ピーター・ドラッカー",
    role: "経営学者",
    category: "business",
  },
  {
    id: "w095",
    kind: "quote",
    text: "心を高め、経営を伸ばす。利他の心なくして、持続する事業はない。",
    author: "稲盛和夫",
    role: "京セラ創業者",
    category: "business",
  },
  {
    id: "w096",
    kind: "quote",
    text: "アメーバ経営——現場の一人ひとりが経営者として考え、採算に責任を持て。",
    author: "稲盛和夫",
    role: "京セラ創業者",
    category: "business",
  },
  {
    id: "w097",
    kind: "quote",
    text: "安くて良いものがあれば、人は必ず買う。あとは、それを本気でやり続けるだけだ。",
    author: "柳井正",
    role: "ファーストリテイリング創業者",
    category: "business",
  },
  {
    id: "w098",
    kind: "anecdote",
    text: "柳井正は「服を変え、常識を変え、世界を変えていく」を掲げ、ユニクロをグローバルSPAへと育てた。在庫も店舗も、すべては顧客の「普段着」の価値に収束させる。",
    author: "柳井正",
    role: "ファーストリテイリング創業者",
    category: "business",
  },
  {
    id: "w099",
    kind: "quote",
    text: "境界のない組織をつくれ。階層よりスピードと率直さを優先せよ。",
    author: "ジャック・ウェルチ",
    role: "元GE CEO",
    category: "business",
  },
  {
    id: "w100",
    kind: "quote",
    text: "変革できない組織は、やがて市場から消える。変化は選択肢ではなく、生存条件だ。",
    author: "ジャック・ウェルチ",
    role: "元GE CEO",
    category: "business",
  },
  {
    id: "w101",
    kind: "quote",
    text: "顧客に何が欲しいか聞いてはいけない。彼らは、まだ存在しないものを言葉にできない。",
    author: "スティーブ・ジョブズ",
    role: "Apple共同創業者",
    category: "business",
  },
  {
    id: "w102",
    kind: "quote",
    text: "シンプルであることは、複雑であることより難しい。だが、たどり着けば山を動かせる。",
    author: "スティーブ・ジョブズ",
    role: "Apple共同創業者",
    category: "business",
  },
  {
    id: "w103",
    kind: "quote",
    text: "人がついてくるのは、権限ではなく信頼からだ。",
    author: "ハワード・シュルツ",
    role: "スターバックス創業者",
    category: "leadership",
  },
  {
    id: "w104",
    kind: "quote",
    text: "優れたリーダーは、聞く時間を最も大切にする。",
    author: "リチャード・ブランソン",
    role: "ヴァージン・グループ創業者",
    category: "leadership",
  },
  {
    id: "w105",
    kind: "quote",
    text: "ビジョンを語れ。数字だけでは人は動かない。",
    author: "ジョン・F・ケネディ",
    role: "アメリカ大統領",
    category: "leadership",
  },
  {
    id: "w106",
    kind: "quote",
    text: "リーダーの仕事は、明日をつくる人材を育てることだ。",
    author: "ジャック・ウェルチ",
    role: "元GE CEO",
    category: "leadership",
  },
  {
    id: "w107",
    kind: "quote",
    text: "決断を先送りするな。曖昧さが組織を腐らせる。",
    author: "コリン・パウエル",
    role: "軍人・政治家",
    category: "leadership",
  },
  {
    id: "w108",
    kind: "quote",
    text: "部下の成功を自分の成功と思える者が、真の上司だ。",
    author: "松下幸之助",
    role: "パナソニック創業者",
    category: "leadership",
  },
  {
    id: "w109",
    kind: "quote",
    text: "指揮とは、命令ではなく方向を示すことだ。",
    author: "アイゼンハワー",
    role: "アメリカ大統領",
    category: "leadership",
  },
  {
    id: "w110",
    kind: "quote",
    text: "人を責める前に、仕組みを疑え。",
    author: "エドワード・デミング",
    role: "品質管理学者",
    category: "leadership",
  },
  {
    id: "w111",
    kind: "quote",
    text: "誠実さは、リーダーシップの通貨である。",
    author: "ブライアン・トレーシー",
    role: "著述家",
    category: "leadership",
  },
  {
    id: "w112",
    kind: "quote",
    text: "チームの力は、最も弱い環ではなく、最も強い信頼で決まる。",
    author: "フィル・ジャクソン",
    role: "バスケットボール指導者",
    category: "leadership",
  },
  {
    id: "w113",
    kind: "quote",
    text: "リーダーは光を浴びるが、影の仕事も引き受ける。",
    author: "ネルソン・マンデラ",
    role: "政治家",
    category: "leadership",
  },
  {
    id: "w114",
    kind: "quote",
    text: "権限は与えられるもの、権威は自ら築くものだ。",
    author: "ジョン・マックスウェル",
    role: "著述家",
    category: "leadership",
  },
  {
    id: "w115",
    kind: "quote",
    text: "現場に立て。机上の地図は現実ではない。",
    author: "豊田英二",
    role: "トヨタ自動車元社長",
    category: "leadership",
  },
  {
    id: "w116",
    kind: "quote",
    text: "誉めるときは人前で、叱るときは二人だけで。",
    author: "メアリー・ケイ・アッシュ",
    role: "起業家",
    category: "leadership",
  },
  {
    id: "w117",
    kind: "quote",
    text: "変化を嫌う組織に、未来はない。",
    author: "アンディ・グローブ",
    role: "元Intel CEO",
    category: "leadership",
  },
  {
    id: "w118",
    kind: "quote",
    text: "部下に聞け。答えはしばしば最前線にある。",
    author: "サム・ウォルトン",
    role: "ウォルマート創業者",
    category: "leadership",
  },
  {
    id: "w119",
    kind: "quote",
    text: "一貫性が、カリスマより長く人を動かす。",
    author: "ジム・コリンズ",
    role: "経営学者",
    category: "leadership",
  },
  {
    id: "w120",
    kind: "quote",
    text: "リーダーは希望を売る。絶望は誰でも売れる。",
    author: "ナポレオン・ボナパルト",
    role: "軍人・皇帝",
    category: "leadership",
  },
  {
    id: "w121",
    kind: "quote",
    text: "小さな約束を守れ。大きな信頼はそこから生まれる。",
    author: "スティーブン・R・コヴィー",
    role: "著述家",
    category: "leadership",
  },
  {
    id: "w122",
    kind: "quote",
    text: "多様性なき会議は、ただの独り言だ。",
    author: "インドラ・ヌーイ",
    role: "元ペプシコCEO",
    category: "leadership",
  },
  {
    id: "w123",
    kind: "quote",
    text: "率先して謝れ。それが組織の安全装置になる。",
    author: "ブレネー・ブラウン",
    role: "研究者",
    category: "leadership",
  },
  {
    id: "w124",
    kind: "quote",
    text: "目標は共有し、手段は委ねよ。",
    author: "ピーター・ドラッカー",
    role: "経営学者",
    category: "leadership",
  },
  {
    id: "w125",
    kind: "quote",
    text: "静かなるリーダーシップも、怒鳴る指揮と同じく力を持つ。",
    author: "老子",
    role: "思想家",
    category: "leadership",
  },
  {
    id: "w126",
    kind: "quote",
    text: "人を育てない成長は、砂上の楼閣だ。",
    author: "稲盛和夫",
    role: "京セラ創業者",
    category: "leadership",
  },
  {
    id: "w127",
    kind: "quote",
    text: "危機のときこそ、平時の文化が露わになる。",
    author: "ウォーレン・ベニス",
    role: "経営学者",
    category: "leadership",
  },
  {
    id: "w128",
    kind: "quote",
    text: "フォロワーがいないリーダーは、ただ散歩しているだけだ。",
    author: "ジョン・マックスウェル",
    role: "著述家",
    category: "leadership",
  },
  {
    id: "w129",
    kind: "quote",
    text: "権限委譲とは、手放す勇気だ。",
    author: "リチャード・ブランソン",
    role: "ヴァージン・グループ創業者",
    category: "leadership",
  },
  {
    id: "w130",
    kind: "quote",
    text: "公正であれ。不公平は才能を殺す。",
    author: "メアリー・バロー",
    role: "元GM CEO",
    category: "leadership",
  },
  {
    id: "w131",
    kind: "quote",
    text: "言葉より先に、行動で示せ。",
    author: "ガンディー",
    role: "独立運動指導者",
    category: "leadership",
  },
  {
    id: "w132",
    kind: "quote",
    text: "組織の天井は、リーダーの器で決まる。",
    author: "ジョン・C・マックスウェル",
    role: "著述家",
    category: "leadership",
  },
  {
    id: "w133",
    kind: "quote",
    text: "傾聴は、最も安くて強力なリーダーシップ技法だ。",
    author: "デール・カーネギー",
    role: "著述家",
    category: "leadership",
  },
  {
    id: "w134",
    kind: "quote",
    text: "反対意見を歓迎せよ。賛成だけの部屋は危険だ。",
    author: "アルフレッド・P・スローン",
    role: "元GM会長",
    category: "leadership",
  },
  {
    id: "w135",
    kind: "quote",
    text: "人を動かすのは恐怖より、意義の共有だ。",
    author: "サイモン・シネック",
    role: "著述家",
    category: "leadership",
  },
  {
    id: "w136",
    kind: "quote",
    text: "成功を分配し、失敗を引き取れ。",
    author: "孫子",
    role: "兵法家",
    category: "leadership",
  },
  {
    id: "w137",
    kind: "quote",
    text: "リーダーは地図ではなく、コンパスを渡せ。",
    author: "スティーブン・R・コヴィー",
    role: "著述家",
    category: "leadership",
  },
  {
    id: "w138",
    kind: "quote",
    text: "現場の声を無視する本社は、やがて現場に無視される。",
    author: "大野耐一",
    role: "トヨタ生産方式",
    category: "leadership",
  },
  {
    id: "w139",
    kind: "quote",
    text: "信頼残高は、毎日の小さな入金で増える。",
    author: "スティーブン・R・コヴィー",
    role: "著述家",
    category: "leadership",
  },
  {
    id: "w140",
    kind: "quote",
    text: "決断の速さは、情報の完全さより重要なことがある。",
    author: "コリン・パウエル",
    role: "軍人・政治家",
    category: "leadership",
  },
  {
    id: "w141",
    kind: "quote",
    text: "誰もが発言できる空気をつくれ。沈黙は危険信号だ。",
    author: "エイミー・エドモンドソン",
    role: "組織心理学者",
    category: "leadership",
  },
  {
    id: "w142",
    kind: "quote",
    text: "現状維持は、最も高いリスクである。",
    author: "マーク・ベニオフ",
    role: "Salesforce創業者",
    category: "innovation",
  },
  {
    id: "w143",
    kind: "quote",
    text: "発明とは、1%のひらめきと、99%の実装だ。",
    author: "トーマス・エジソン",
    role: "発明家",
    category: "innovation",
  },
  {
    id: "w144",
    kind: "quote",
    text: "顧客の不満の中に、次の製品がある。",
    author: "本田宗一郎",
    role: "ホンダ創業者",
    category: "innovation",
  },
  {
    id: "w145",
    kind: "quote",
    text: "新しいものは、最初は嘲笑され、次に反対され、やがて当たり前になる。",
    author: "マハトマ・ガンディー",
    role: "独立運動指導者",
    category: "innovation",
  },
  {
    id: "w146",
    kind: "quote",
    text: "実験なき戦略は、ただの願望だ。",
    author: "ジェフ・ベゾス",
    role: "Amazon創業者",
    category: "innovation",
  },
  {
    id: "w147",
    kind: "quote",
    text: "破壊される側より、破壊する側に回れ。",
    author: "クレイトン・クリステンセン",
    role: "経営学者",
    category: "innovation",
  },
  {
    id: "w148",
    kind: "quote",
    text: "小さく試し、大きく展開せよ。",
    author: "エリック・リース",
    role: "起業家",
    category: "innovation",
  },
  {
    id: "w149",
    kind: "quote",
    text: "技術は手段。目的は人の体験だ。",
    author: "ジョナサン・アイブ",
    role: "デザイナー",
    category: "innovation",
  },
  {
    id: "w150",
    kind: "quote",
    text: "昨日の成功体験が、今日のイノベーションを殺す。",
    author: "クレイトン・クリステンセン",
    role: "経営学者",
    category: "innovation",
  },
  {
    id: "w151",
    kind: "quote",
    text: "常識を疑え。常識は過去の最適解にすぎない。",
    author: "スティーブ・ジョブズ",
    role: "Apple共同創業者",
    category: "innovation",
  },
  {
    id: "w152",
    kind: "quote",
    text: "失敗はデータだ。恥ではない。",
    author: "アストロ・テラー",
    role: "Google X",
    category: "innovation",
  },
  {
    id: "w153",
    kind: "quote",
    text: "未来の顧客は、今のアンケートには現れない。",
    author: "ヘンリー・フォード",
    role: "フォード創業者",
    category: "innovation",
  },
  {
    id: "w154",
    kind: "quote",
    text: "スピードは品質の敵ではない。遅さの言い訳だ。",
    author: "リード・ヘイスティングス",
    role: "Netflix共同創業者",
    category: "innovation",
  },
  {
    id: "w155",
    kind: "quote",
    text: "真似から学べ。ただし、そこで止まるな。",
    author: "ピカソ（通説）",
    role: "芸術家",
    category: "innovation",
  },
  {
    id: "w156",
    kind: "quote",
    text: "制約は創造の母である。",
    author: "イゴール・ストラヴィンスキー",
    role: "作曲家",
    category: "innovation",
  },
  {
    id: "w157",
    kind: "quote",
    text: "プロトタイプは千の会議に勝る。",
    author: "IDEOの原則",
    role: "デザインファーム",
    category: "innovation",
  },
  {
    id: "w158",
    kind: "quote",
    text: "市場が無いのではなく、まだ見えていないだけだ。",
    author: "ピーター・ティール",
    role: "起業家",
    category: "innovation",
  },
  {
    id: "w159",
    kind: "quote",
    text: "イノベーションは会議室ではなく、現場で起きる。",
    author: "トヨタの思想",
    role: "製造業",
    category: "innovation",
  },
  {
    id: "w160",
    kind: "quote",
    text: "古い地図で新しい土地は歩けない。",
    author: "アルヴィン・トフラー",
    role: "未来学者",
    category: "innovation",
  },
  {
    id: "w161",
    kind: "quote",
    text: "好奇心は、組織の研究開発予算より安い燃料だ。",
    author: "アインシュタイン",
    role: "物理学者",
    category: "innovation",
  },
  {
    id: "w162",
    kind: "quote",
    text: "完璧を待つな。出荷して学べ。",
    author: "リード・ホフマン",
    role: "LinkedIn共同創業者",
    category: "innovation",
  },
  {
    id: "w163",
    kind: "quote",
    text: "異分野の交差点に、新しい価値が生まれる。",
    author: "フランス・ヨハンソン",
    role: "著述家",
    category: "innovation",
  },
  {
    id: "w164",
    kind: "quote",
    text: "既存の延長線上に、飛躍はない。",
    author: "孫正義",
    role: "ソフトバンクグループ創業者",
    category: "innovation",
  },
  {
    id: "w165",
    kind: "quote",
    text: "ユーザーの行動を観察せよ。言葉より正直だ。",
    author: "ドン・ノーマン",
    role: "デザイン研究者",
    category: "innovation",
  },
  {
    id: "w166",
    kind: "quote",
    text: "発明の瞬間より、普及の設計が事業を決める。",
    author: "エヴェレット・ロジャース",
    role: "社会学者",
    category: "innovation",
  },
  {
    id: "w167",
    kind: "quote",
    text: "大胆であれ。ただし計測を忘れるな。",
    author: "ピーター・ドラッカー",
    role: "経営学者",
    category: "innovation",
  },
  {
    id: "w168",
    kind: "quote",
    text: "新しい技術は、古い問題を新しい角度から解く。",
    author: "ティム・バーナーズ＝リー",
    role: "WWW発明者",
    category: "innovation",
  },
  {
    id: "w169",
    kind: "quote",
    text: "創造性は才能ではなく、習慣だ。",
    author: "ツイラ・サープ",
    role: "振付家",
    category: "innovation",
  },
  {
    id: "w170",
    kind: "quote",
    text: "競合を見るな。顧客の未充足を見よ。",
    author: "ピーター・ドラッカー",
    role: "経営学者",
    category: "innovation",
  },
  {
    id: "w171",
    kind: "quote",
    text: "デジタル化とは、紙を画面に移すことではない。仕事の再設計だ。",
    author: "エリック・シュミット",
    role: "元Google CEO",
    category: "innovation",
  },
  {
    id: "w172",
    kind: "quote",
    text: "実験文化なき企業は、運に依存する。",
    author: "イーロン・マスク",
    role: "起業家",
    category: "innovation",
  },
  {
    id: "w173",
    kind: "quote",
    text: "シンプルな解は、複雑な理解の末に現れる。",
    author: "レオナルド・ダ・ヴィンチ",
    role: "芸術家",
    category: "innovation",
  },
  {
    id: "w174",
    kind: "quote",
    text: "イノベーションの敵は、失敗ではなく無関心だ。",
    author: "セス・ゴーディン",
    role: "著述家",
    category: "innovation",
  },
  {
    id: "w175",
    kind: "quote",
    text: "明日の当たり前を、今日の非常識として始めよ。",
    author: "ジャック・マー",
    role: "アリババ創業者",
    category: "innovation",
  },
  {
    id: "w176",
    kind: "quote",
    text: "問いを変えれば、答えの地図も変わる。",
    author: "アインシュタイン",
    role: "物理学者",
    category: "innovation",
  },
  {
    id: "w177",
    kind: "quote",
    text: "技術負債を無視する成長は、いつか止まる。",
    author: "ウォード・カニンガム",
    role: "プログラマ",
    category: "innovation",
  },
  {
    id: "w178",
    kind: "quote",
    text: "オープンな協働が、閉じた秘密より速く進む。",
    author: "ライナス・トーバルズ",
    role: "Linux",
    category: "innovation",
  },
  {
    id: "w179",
    kind: "quote",
    text: "続ける者が、才能を追い越す。",
    author: "カルヴィン・クーリッジ",
    role: "アメリカ大統領",
    category: "perseverance",
  },
  {
    id: "w180",
    kind: "quote",
    text: "落馬しても、また鞍に乗れ。",
    author: "カウボーイの諺",
    role: "ことわざ",
    category: "perseverance",
  },
  {
    id: "w181",
    kind: "quote",
    text: "大きな成果は、退屈な反復の先にある。",
    author: "エピクロス",
    role: "哲学者",
    category: "perseverance",
  },
  {
    id: "w182",
    kind: "quote",
    text: "あきらめた瞬間が、本当の敗北だ。",
    author: "リチャード・ニクソン",
    role: "アメリカ大統領",
    category: "perseverance",
  },
  {
    id: "w183",
    kind: "quote",
    text: "困難は、成長の入口にすぎない。",
    author: "ヘレン・ケラー",
    role: "著述家",
    category: "perseverance",
  },
  {
    id: "w184",
    kind: "quote",
    text: "千里の道も一歩から。ただし歩みを止めないことだ。",
    author: "老子",
    role: "思想家",
    category: "perseverance",
  },
  {
    id: "w185",
    kind: "quote",
    text: "成功は一夜にして来ない。準備の夜が続くだけだ。",
    author: "成功の諺",
    role: "ことわざ",
    category: "perseverance",
  },
  {
    id: "w186",
    kind: "quote",
    text: "折れない心は、折れた経験から鍛えられる。",
    author: "ニーチェ",
    role: "哲学者",
    category: "perseverance",
  },
  {
    id: "w187",
    kind: "quote",
    text: "今日の小さな努力が、明日の大きな差になる。",
    author: "ダーウィン",
    role: "生物学者",
    category: "perseverance",
  },
  {
    id: "w188",
    kind: "quote",
    text: "雨の日も種を蒔け。晴天だけを待つな。",
    author: "農家の知恵",
    role: "ことわざ",
    category: "perseverance",
  },
  {
    id: "w189",
    kind: "quote",
    text: "何度転んでも、起き上がる回数を数えよ。",
    author: "孔子",
    role: "思想家",
    category: "perseverance",
  },
  {
    id: "w190",
    kind: "quote",
    text: "忍耐とは、待つことではない。待ちながら働くことだ。",
    author: "マーガレット・サッチャー",
    role: "政治家",
    category: "perseverance",
  },
  {
    id: "w191",
    kind: "quote",
    text: "長い坂の途中では、景色より足元を見よ。",
    author: "宮本武蔵",
    role: "剣豪",
    category: "perseverance",
  },
  {
    id: "w192",
    kind: "quote",
    text: "情熱は点火し、規律が燃え続ける。",
    author: "アンジェラ・ダックワース",
    role: "心理学者",
    category: "perseverance",
  },
  {
    id: "w193",
    kind: "quote",
    text: "やり遂げるまで、途中経過を成功と呼ぶな。",
    author: "ウィンストン・チャーチル",
    role: "政治家",
    category: "perseverance",
  },
  {
    id: "w194",
    kind: "quote",
    text: "石橋を叩いて渡るな。叩きすぎて渡れなくなる。",
    author: "日本の戒め",
    role: "ことわざ",
    category: "perseverance",
  },
  {
    id: "w195",
    kind: "quote",
    text: "才能は入口、継続が出入口だ。",
    author: "イチロー",
    role: "野球選手",
    category: "perseverance",
  },
  {
    id: "w196",
    kind: "quote",
    text: "挫折は、方向転換の合図かもしれない。",
    author: "ヘンリー・フォード",
    role: "フォード創業者",
    category: "perseverance",
  },
  {
    id: "w197",
    kind: "quote",
    text: "ゆっくりでよい。止まらなければ前へ進む。",
    author: "孔子",
    role: "思想家",
    category: "perseverance",
  },
  {
    id: "w198",
    kind: "quote",
    text: "粘り強さは、華やかさより結果に近い。",
    author: "トーマス・エジソン",
    role: "発明家",
    category: "perseverance",
  },
  {
    id: "w199",
    kind: "quote",
    text: "嵐を呪うより、雨具を作れ。",
    author: "実務の知恵",
    role: "ことわざ",
    category: "perseverance",
  },
  {
    id: "w200",
    kind: "quote",
    text: "目標が遠ければ、分割して近づけ。",
    author: "ブライアン・トレーシー",
    role: "著述家",
    category: "perseverance",
  },
  {
    id: "w201",
    kind: "quote",
    text: "努力は裏切らない。ただし方法は疑え。",
    author: "福沢諭吉",
    role: "思想家",
    category: "perseverance",
  },
  {
    id: "w202",
    kind: "quote",
    text: "苦しいときほど、基本に戻れ。",
    author: "ジョン・ウッドン",
    role: "指導者",
    category: "perseverance",
  },
  {
    id: "w203",
    kind: "quote",
    text: "継続の反対は休息ではない。放棄だ。",
    author: "セネカ",
    role: "哲学者",
    category: "perseverance",
  },
  {
    id: "w204",
    kind: "quote",
    text: "大きな夢は、小さな日課で運ばれる。",
    author: "ロバート・コリアー",
    role: "著述家",
    category: "perseverance",
  },
  {
    id: "w205",
    kind: "quote",
    text: "失敗の数を恥じるな。挑戦の数を誇れ。",
    author: "マイケル・ジョーダン",
    role: "バスケットボール選手",
    category: "perseverance",
  },
  {
    id: "w206",
    kind: "quote",
    text: "道は、歩き続ける者の前にだけ続く。",
    author: "ゲーテ",
    role: "詩人",
    category: "perseverance",
  },
  {
    id: "w207",
    kind: "quote",
    text: "忍耐は受動ではない。能動的な選択だ。",
    author: "ヴィクトール・フランクル",
    role: "精神科医",
    category: "perseverance",
  },
  {
    id: "w208",
    kind: "quote",
    text: "一度の勝利より、百回の再起を尊べ。",
    author: "日本の武道精神",
    role: "ことわざ",
    category: "perseverance",
  },
  {
    id: "w209",
    kind: "quote",
    text: "疲れても、方向だけは見失うな。",
    author: "ダライ・ラマ",
    role: "宗教指導者",
    category: "perseverance",
  },
  {
    id: "w210",
    kind: "quote",
    text: "成果が出ない日も、習慣は資産になる。",
    author: "ジェームズ・クリアー",
    role: "著述家",
    category: "perseverance",
  },
  {
    id: "w211",
    kind: "quote",
    text: "長く続ける秘訣は、楽しさを設計することだ。",
    author: "宮本武蔵",
    role: "剣豪",
    category: "perseverance",
  },
  {
    id: "w212",
    kind: "quote",
    text: "壁は止まれの合図ではない。回り道の地図だ。",
    author: "ことわざ",
    role: "ことわざ",
    category: "perseverance",
  },
  {
    id: "w213",
    kind: "quote",
    text: "粘る者は運を待つ。諦める者は運を逃す。",
    author: "セネカ",
    role: "哲学者",
    category: "perseverance",
  },
  {
    id: "w214",
    kind: "quote",
    text: "今日やれることを、明日に売信用貸するな。",
    author: "ベンジャミン・フランクリン",
    role: "政治家",
    category: "perseverance",
  },
  {
    id: "w215",
    kind: "anecdote",
    text: "挫折のあとに残るのは、経験という資本だ。",
    author: "ヘンリー・フォード",
    role: "フォード創業者",
    category: "perseverance",
  },
  {
    id: "w216",
    kind: "quote",
    text: "知る者は言わず、言う者は知らず。",
    author: "老子",
    role: "思想家",
    category: "wisdom",
  },
  {
    id: "w217",
    kind: "quote",
    text: "疑うことを学べ。しかし、疑うだけで終わるな。",
    author: "デカルト",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w218",
    kind: "quote",
    text: "沈黙もまた、ひとつの答えである。",
    author: "ユング",
    role: "心理学者",
    category: "wisdom",
  },
  {
    id: "w219",
    kind: "quote",
    text: "簡潔さは、知性の最高の形だ。",
    author: "シセロ",
    role: "政治家",
    category: "wisdom",
  },
  {
    id: "w220",
    kind: "quote",
    text: "怒りに駆られる前に、十まで数えよ。",
    author: "トーマス・ジェファーソン",
    role: "アメリカ大統領",
    category: "wisdom",
  },
  {
    id: "w221",
    kind: "quote",
    text: "自分の無知を知る者が、いちばん賢い。",
    author: "ソクラテス",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w222",
    kind: "quote",
    text: "真実は単純だが、単純さは難しい。",
    author: "オスカー・ワイルド",
    role: "作家",
    category: "wisdom",
  },
  {
    id: "w223",
    kind: "quote",
    text: "判断を急ぐな。理解を急げ。",
    author: "エピクロス",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w224",
    kind: "quote",
    text: "心の平静は、外の静寂ではなく内の整理から来る。",
    author: "マルクス・アウレリウス",
    role: "ローマ皇帝",
    category: "wisdom",
  },
  {
    id: "w225",
    kind: "quote",
    text: "言葉を選べ。言葉は現実をつくる。",
    author: "ウィトゲンシュタイン",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w226",
    kind: "quote",
    text: "比較は知恵を曇らせる。観察は知恵を澄ませる。",
    author: "仏教の教え",
    role: "宗教",
    category: "wisdom",
  },
  {
    id: "w227",
    kind: "quote",
    text: "短い知恵は、長い説明に勝ることがある。",
    author: "パスカル",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w228",
    kind: "quote",
    text: "欲を知らぬ者は貧しい。足るを知る者は富む。",
    author: "老子",
    role: "思想家",
    category: "wisdom",
  },
  {
    id: "w229",
    kind: "quote",
    text: "時間は最も公平で、最も容赦ない資源だ。",
    author: "セネカ",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w230",
    kind: "quote",
    text: "問いを持て。答えより問いに価値があることがある。",
    author: "アインシュタイン",
    role: "物理学者",
    category: "wisdom",
  },
  {
    id: "w231",
    kind: "quote",
    text: "他人の欠点を探す暇で、自分の短所を直せ。",
    author: "孔子",
    role: "思想家",
    category: "wisdom",
  },
  {
    id: "w232",
    kind: "quote",
    text: "知恵は年齢ではなく、反省の回数で増える。",
    author: "キケロ",
    role: "政治家",
    category: "wisdom",
  },
  {
    id: "w233",
    kind: "quote",
    text: "静かに考える時間を、スケジュールに入れよ。",
    author: "パスカル",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w234",
    kind: "quote",
    text: "感情は信号だ。主人にしてはいけない。",
    author: "ストア派の教え",
    role: "哲学",
    category: "wisdom",
  },
  {
    id: "w235",
    kind: "quote",
    text: "今日の確信を、明日の仮説として扱え。",
    author: "科学的態度",
    role: "科学",
    category: "wisdom",
  },
  {
    id: "w236",
    kind: "quote",
    text: "聞くことは、話すことの二倍学べる。",
    author: "エピクロス",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w237",
    kind: "quote",
    text: "複雑さに逃げず、本質に切り込め。",
    author: "オッカム",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w238",
    kind: "quote",
    text: "運命を呪うより、選択を磨け。",
    author: "セネカ",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w239",
    kind: "quote",
    text: "知恵の始まりは、驚きである。",
    author: "アリストテレス",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w240",
    kind: "quote",
    text: "小さな善を積み重ねよ。大きな徳はそこから生まれる。",
    author: "アリストテレス",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w241",
    kind: "quote",
    text: "忘れる技術も、覚える技術と同じく大切だ。",
    author: "ニーチェ",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w242",
    kind: "quote",
    text: "他人を変える前に、自分の見方を変えよ。",
    author: "アドラー",
    role: "心理学者",
    category: "wisdom",
  },
  {
    id: "w243",
    kind: "quote",
    text: "沈黙のうちに、多くの真実が語られる。",
    author: "リルケ",
    role: "詩人",
    category: "wisdom",
  },
  {
    id: "w244",
    kind: "quote",
    text: "バランスは停滞ではない。動的な調和だ。",
    author: "ヘーラクレイトス",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w245",
    kind: "quote",
    text: "知識は力だが、知恵は舵だ。",
    author: "フランシス・ベーコン",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w246",
    kind: "quote",
    text: "完璧を求めるな。十分を見極めよ。",
    author: "ヴォルテール",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w247",
    kind: "quote",
    text: "今日の不安の大半は、起きない未来だ。",
    author: "セネカ",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w248",
    kind: "quote",
    text: "謙虚さは、学びの入り口である。",
    author: "ソクラテス",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w249",
    kind: "quote",
    text: "矛盾を恐れるな。現実は矛盾を含む。",
    author: "ヘーゲル",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w250",
    kind: "quote",
    text: "短く生きるな。深く生きよ。",
    author: "セネカ",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w251",
    kind: "quote",
    text: "知恵は共有されて初めて光る。",
    author: "仏教の教え",
    role: "宗教",
    category: "wisdom",
  },
  {
    id: "w252",
    kind: "quote",
    text: "自分の意見を疑える者が、成熟している。",
    author: "ジョン・スチュアート・ミル",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w253",
    kind: "quote",
    text: "キャッシュは酸素だ。利益は食事だ。両方必要だ。",
    author: "起業の格言",
    role: "経営",
    category: "business",
  },
  {
    id: "w254",
    kind: "quote",
    text: "顧客が去る理由を、数字より物語で聞け。",
    author: "顧客志向の教え",
    role: "経営",
    category: "business",
  },
  {
    id: "w255",
    kind: "quote",
    text: "価格競争に入った瞬間、差別化を放棄している。",
    author: "マイケル・ポーター",
    role: "経営学者",
    category: "business",
  },
  {
    id: "w256",
    kind: "quote",
    text: "組織図より、情報の流れを設計せよ。",
    author: "ビル・ゲイツ",
    role: "Microsoft共同創業者",
    category: "business",
  },
  {
    id: "w257",
    kind: "quote",
    text: "採用は最重要の投資である。",
    author: "リード・ヘイスティングス",
    role: "Netflix共同創業者",
    category: "business",
  },
  {
    id: "w258",
    kind: "quote",
    text: "文化は戦略を朝食にする。",
    author: "ピーター・ドラッカー",
    role: "経営学者",
    category: "business",
  },
  {
    id: "w259",
    kind: "quote",
    text: "短期の数字のために、長期の信頼を売るな。",
    author: "ウォーレン・バフェット",
    role: "投資家",
    category: "business",
  },
  {
    id: "w260",
    kind: "quote",
    text: "シンプルなビジネスモデルは、実行で複雑になる。最初から複雑にするな。",
    author: "ジャック・ウェルチ",
    role: "元GE CEO",
    category: "business",
  },
  {
    id: "w261",
    kind: "quote",
    text: "競合分析は必要だが、顧客観察の代わりにはならない。",
    author: "ジェフ・ベゾス",
    role: "Amazon創業者",
    category: "business",
  },
  {
    id: "w262",
    kind: "quote",
    text: "利益なき成長は、ただの忙しさだ。",
    author: "ピーター・ドラッカー",
    role: "経営学者",
    category: "business",
  },
  {
    id: "w263",
    kind: "quote",
    text: "現場の改善を止めた会社は、静かに衰退する。",
    author: "大野耐一",
    role: "トヨタ生産方式",
    category: "business",
  },
  {
    id: "w264",
    kind: "quote",
    text: "ブランドは広告ではなく、体験の蓄積だ。",
    author: "ジェフ・ベゾス",
    role: "Amazon創業者",
    category: "business",
  },
  {
    id: "w265",
    kind: "quote",
    text: "意思決定の遅さが、最大のコストになることがある。",
    author: "アンディ・グローブ",
    role: "元Intel CEO",
    category: "business",
  },
  {
    id: "w266",
    kind: "quote",
    text: "社員が誇りを持てない商品は、長く売れない。",
    author: "盛田昭夫",
    role: "ソニー共同創業者",
    category: "business",
  },
  {
    id: "w267",
    kind: "quote",
    text: "値下げは最後の手段。価値上げが先決だ。",
    author: "稲盛和夫",
    role: "京セラ創業者",
    category: "business",
  },
  {
    id: "w268",
    kind: "quote",
    text: "在庫は罪にも資産にもなる。見極めよ。",
    author: "柳井正",
    role: "ファーストリテイリング創業者",
    category: "business",
  },
  {
    id: "w269",
    kind: "quote",
    text: "経営者の仕事は、資源を成果に変換することだ。",
    author: "ピーター・ドラッカー",
    role: "経営学者",
    category: "business",
  },
  {
    id: "w270",
    kind: "quote",
    text: "小さな市場で一番になれ。それから広げよ。",
    author: "ピーター・ティール",
    role: "起業家",
    category: "business",
  },
  {
    id: "w271",
    kind: "quote",
    text: "会議の目的は合意ではなく、決断だ。",
    author: "ジェフ・ベゾス",
    role: "Amazon創業者",
    category: "business",
  },
  {
    id: "w272",
    kind: "quote",
    text: "顧客生涯価値を見よ。一回の取引で判断するな。",
    author: "サブスク時代の教え",
    role: "経営",
    category: "business",
  },
  {
    id: "w273",
    kind: "quote",
    text: "透明性は、管理コストを下げる。",
    author: "レイ・ダリオ",
    role: "投資家",
    category: "business",
  },
  {
    id: "w274",
    kind: "quote",
    text: "事業計画は仮説だ。検証なき計画は小説だ。",
    author: "エリック・リース",
    role: "起業家",
    category: "business",
  },
  {
    id: "w275",
    kind: "quote",
    text: "良い財務は、悪い戦略を救えない。",
    author: "ウォーレン・バフェット",
    role: "投資家",
    category: "business",
  },
  {
    id: "w276",
    kind: "quote",
    text: "スピードと品質は両立できる。手順を疑え。",
    author: "トヨタの思想",
    role: "製造業",
    category: "business",
  },
  {
    id: "w277",
    kind: "quote",
    text: "パートナーシップは契約書より信頼で持つ。",
    author: "松下幸之助",
    role: "パナソニック創業者",
    category: "business",
  },
  {
    id: "w278",
    kind: "quote",
    text: "成長の痛みを避けて、成長の果実だけを望むな。",
    author: "リチャード・ブランソン",
    role: "ヴァージン・グループ創業者",
    category: "business",
  },
  {
    id: "w279",
    kind: "quote",
    text: "データなき議論は、意見の交換にすぎない。",
    author: "W・エドワーズ・デミング",
    role: "品質管理",
    category: "business",
  },
  {
    id: "w280",
    kind: "quote",
    text: "退出戦略より、価値創造戦略を先に語れ。",
    author: "ピーター・ドラッカー",
    role: "経営学者",
    category: "business",
  },
  {
    id: "w281",
    kind: "quote",
    text: "組織の肥満は、会議と承認の過多から始まる。",
    author: "ジャック・ウェルチ",
    role: "元GE CEO",
    category: "business",
  },
  {
    id: "w282",
    kind: "quote",
    text: "顧客の時間を奪うな。それが最大の失礼だ。",
    author: "ジェフ・ベゾス",
    role: "Amazon創業者",
    category: "business",
  },
  {
    id: "w283",
    kind: "quote",
    text: "事業の本質は、約束を守り続けることだ。",
    author: "渋沢栄一",
    role: "実業家",
    category: "business",
  },
  {
    id: "w284",
    kind: "quote",
    text: "リスクを取らないことが、最大のリスクになる。",
    author: "マーク・ザッカーバーグ",
    role: "Meta創業者",
    category: "business",
  },
  {
    id: "w285",
    kind: "quote",
    text: "コスト削減は手段。価値毀損が目的になってはいけない。",
    author: "経営の戒め",
    role: "経営",
    category: "business",
  },
  {
    id: "w286",
    kind: "quote",
    text: "現場が強い会社は、本部が謙虚だ。",
    author: "本田宗一郎",
    role: "ホンダ創業者",
    category: "business",
  },
  {
    id: "w287",
    kind: "quote",
    text: "数字は真実の一部。文脈が残りを語る。",
    author: "ピーター・ドラッカー",
    role: "経営学者",
    category: "business",
  },
  {
    id: "w288",
    kind: "quote",
    text: "採用を急ぐな。誤採用のコストは計り知れない。",
    author: "スティーブ・ジョブズ",
    role: "Apple共同創業者",
    category: "business",
  },
  {
    id: "w289",
    kind: "quote",
    text: "競合より、昨日の自分を超えよ。",
    author: "柳井正",
    role: "ファーストリテイリング創業者",
    category: "business",
  },
  {
    id: "w290",
    kind: "quote",
    text: "利益は目的ではなく、健全さの指標だ。",
    author: "ピーター・ドラッカー",
    role: "経営学者",
    category: "business",
  },
  {
    id: "w291",
    kind: "quote",
    text: "長期株主と短期投機を混同するな。",
    author: "ウォーレン・バフェット",
    role: "投資家",
    category: "business",
  },
  {
    id: "w292",
    kind: "quote",
    text: "怖いからこそ、やる価値がある。",
    author: "マーク・トウェイン",
    role: "作家",
    category: "courage",
  },
  {
    id: "w293",
    kind: "quote",
    text: "安全地帯の外に、成長がある。",
    author: "ネール・ドナルド・ウォルシュ",
    role: "著述家",
    category: "courage",
  },
  {
    id: "w294",
    kind: "quote",
    text: "勇気とは、完璧な準備ができるまで待たないことだ。",
    author: "アメリカ陸軍の格言",
    role: "軍事",
    category: "courage",
  },
  {
    id: "w295",
    kind: "quote",
    text: "一歩踏み出せ。道はあとから現れる。",
    author: "ゲーテ",
    role: "詩人",
    category: "courage",
  },
  {
    id: "w296",
    kind: "quote",
    text: "沈黙は安全だが、進歩ではない。",
    author: "マーティン・ルーサー・キング・ジュニア",
    role: "公民権運動",
    category: "courage",
  },
  {
    id: "w297",
    kind: "quote",
    text: "恐れを消すな。恐れと並走せよ。",
    author: "スーザン・ジェフワーズ",
    role: "著述家",
    category: "courage",
  },
  {
    id: "w298",
    kind: "quote",
    text: "反対されても、正しいと思うなら進め。",
    author: "ガリレオ",
    role: "科学者",
    category: "courage",
  },
  {
    id: "w299",
    kind: "quote",
    text: "勇気の欠如は、機会の損失として現れる。",
    author: "アンブローズ・レッドムーン",
    role: "著述家",
    category: "courage",
  },
  {
    id: "w300",
    kind: "quote",
    text: "初めての挑戦に、慣れは必要ない。",
    author: "未知への一歩",
    role: "ことわざ",
    category: "courage",
  },
  {
    id: "w301",
    kind: "quote",
    text: "リスクを取る者だけが、風を感じられる。",
    author: "ヨットの知恵",
    role: "ことわざ",
    category: "courage",
  },
  {
    id: "w302",
    kind: "quote",
    text: "勇気は筋肉だ。使わなければ萎える。",
    author: "マヤ・アンジェロウ",
    role: "詩人",
    category: "courage",
  },
  {
    id: "w303",
    kind: "quote",
    text: "世間体より、良心に従え。",
    author: "ソクラテス",
    role: "哲学者",
    category: "courage",
  },
  {
    id: "w304",
    kind: "quote",
    text: "失敗を恐れるな。挑戦しないことを恐れよ。",
    author: "マイケル・ジョーダン",
    role: "バスケットボール選手",
    category: "courage",
  },
  {
    id: "w305",
    kind: "quote",
    text: "弱い者ほど、強く見せようとする。強い者は弱さを認める。",
    author: "ブレネー・ブラウン",
    role: "研究者",
    category: "courage",
  },
  {
    id: "w306",
    kind: "quote",
    text: "正義のために立つとき、孤独でも立て。",
    author: "ネルソン・マンデラ",
    role: "政治家",
    category: "courage",
  },
  {
    id: "w307",
    kind: "quote",
    text: "勇気がいる選択は、たいてい正しい方向にある。",
    author: "人生の観察",
    role: "ことわざ",
    category: "courage",
  },
  {
    id: "w308",
    kind: "quote",
    text: "始めなければ、終わりもない。",
    author: "ゲーテ",
    role: "詩人",
    category: "courage",
  },
  {
    id: "w309",
    kind: "quote",
    text: "恐怖は拡大鏡だ。近づくと小さくなる。",
    author: "ラルフ・ウォルドー・エマーソン",
    role: "思想家",
    category: "courage",
  },
  {
    id: "w310",
    kind: "quote",
    text: "反対意見に耐える力が、自由の条件だ。",
    author: "ヴォルテール",
    role: "哲学者",
    category: "courage",
  },
  {
    id: "w311",
    kind: "quote",
    text: "勇気とは、他者のために声を上げることでもある。",
    author: "エリ・ヴィーゼル",
    role: "著述家",
    category: "courage",
  },
  {
    id: "w312",
    kind: "quote",
    text: "未知を避けて生きると、既知の檻に入る。",
    author: "ジョセフ・キャンベル",
    role: "神話学者",
    category: "courage",
  },
  {
    id: "w313",
    kind: "quote",
    text: "一歩の勇気が、百の計画に勝る。",
    author: "実行の格言",
    role: "ことわざ",
    category: "courage",
  },
  {
    id: "w314",
    kind: "quote",
    text: "恐れを言葉にすると、半分は小さくなる。",
    author: "ことわざ",
    role: "ことわざ",
    category: "courage",
  },
  {
    id: "w315",
    kind: "quote",
    text: "勇気ある質問が、停滞を破る。",
    author: "科学の精神",
    role: "科学",
    category: "courage",
  },
  {
    id: "w316",
    kind: "quote",
    text: "安全な選択が、人生を狭くすることがある。",
    author: "アナイス・ニン",
    role: "作家",
    category: "courage",
  },
  {
    id: "w317",
    kind: "quote",
    text: "立ち上がる理由は、転んだ回数より大切だ。",
    author: "アフリカの諺",
    role: "ことわざ",
    category: "courage",
  },
  {
    id: "w318",
    kind: "quote",
    text: "勇気は生まれつきではない。選ぶものだ。",
    author: "マヤ・アンジェロウ",
    role: "詩人",
    category: "courage",
  },
  {
    id: "w319",
    kind: "quote",
    text: "困難の正面に立て。側面からは大きく見える。",
    author: "軍事の知恵",
    role: "軍事",
    category: "courage",
  },
  {
    id: "w320",
    kind: "quote",
    text: "自分の声で話せ。借り物の勇気は続かない。",
    author: "オスカー・ワイルド",
    role: "作家",
    category: "courage",
  },
  {
    id: "w321",
    kind: "quote",
    text: "最初の拒絶を、最終判決にするな。",
    author: "営業の知恵",
    role: "ことわざ",
    category: "courage",
  },
  {
    id: "w322",
    kind: "quote",
    text: "勇気とは、愛する人を守る決断でもある。",
    author: "人生の観察",
    role: "ことわざ",
    category: "courage",
  },
  {
    id: "w323",
    kind: "quote",
    text: "不安の中でも、次の一手を打て。",
    author: "ストア派の教え",
    role: "哲学",
    category: "courage",
  },
  {
    id: "w324",
    kind: "quote",
    text: "世間の拍手より、自分の納得を選べ。",
    author: "キルケゴール",
    role: "哲学者",
    category: "courage",
  },
  {
    id: "w325",
    kind: "quote",
    text: "挑戦の前に、完璧な自信は来ない。",
    author: "行動心理学",
    role: "心理",
    category: "courage",
  },
  {
    id: "w326",
    kind: "quote",
    text: "勇気は孤独な瞬間に試される。",
    author: "文学の観察",
    role: "ことわざ",
    category: "courage",
  },
  {
    id: "w327",
    kind: "quote",
    text: "怖い橋を渡った者だけが、向こう岸を知る。",
    author: "旅の知恵",
    role: "ことわざ",
    category: "courage",
  },
  {
    id: "w328",
    kind: "quote",
    text: "勇気ある失敗は、臆病な成功より尊い。",
    author: "ジョージ・パットン",
    role: "軍人",
    category: "courage",
  },
  {
    id: "w329",
    kind: "quote",
    text: "人生は選択の連続だ。選ばないことも選択だ。",
    author: "ジャン＝ポール・サルトル",
    role: "哲学者",
    category: "life",
  },
  {
    id: "w330",
    kind: "quote",
    text: "今日を生きよ。昨日は経験、明日は希望。",
    author: "ラテン語の諺",
    role: "ことわざ",
    category: "life",
  },
  {
    id: "w331",
    kind: "quote",
    text: "シンプルに暮らせ。心は広くなる。",
    author: "ヘンリー・デイヴィッド・ソロー",
    role: "思想家",
    category: "life",
  },
  {
    id: "w332",
    kind: "quote",
    text: "感謝は、幸福の最短ルートだ。",
    author: "キケロ",
    role: "政治家",
    category: "life",
  },
  {
    id: "w333",
    kind: "quote",
    text: "忙しさを、充実と取り違えるな。",
    author: "ソクラテス",
    role: "哲学者",
    category: "life",
  },
  {
    id: "w334",
    kind: "quote",
    text: "人生の質は、長い時間ではなく深い瞬間で決まる。",
    author: "モンテーニュ",
    role: "随筆家",
    category: "life",
  },
  {
    id: "w335",
    kind: "quote",
    text: "他人の人生を生きるな。自分の物語を書け。",
    author: "スティーブ・ジョブズ",
    role: "Apple共同創業者",
    category: "life",
  },
  {
    id: "w336",
    kind: "quote",
    text: "小さな喜びを見逃すな。それが日常の豊かさだ。",
    author: "エピクロス",
    role: "哲学者",
    category: "life",
  },
  {
    id: "w337",
    kind: "quote",
    text: "健康は最大の富、満足は最大の宝だ。",
    author: "仏教の教え",
    role: "宗教",
    category: "life",
  },
  {
    id: "w338",
    kind: "quote",
    text: "別れは終わりではなく、形を変えた続きでもある。",
    author: "リルケ",
    role: "詩人",
    category: "life",
  },
  {
    id: "w339",
    kind: "quote",
    text: "人生に意味を求めるな。意味をつくれ。",
    author: "ヴィクトール・フランクル",
    role: "精神科医",
    category: "life",
  },
  {
    id: "w340",
    kind: "quote",
    text: "笑うことは、抵抗であり回復だ。",
    author: "チャーリー・チャップリン",
    role: "喜劇俳優",
    category: "life",
  },
  {
    id: "w341",
    kind: "quote",
    text: "余白のない人生は、息が詰まる。",
    author: "日本の美意識",
    role: "ことわざ",
    category: "life",
  },
  {
    id: "w342",
    kind: "quote",
    text: "愛する人に、今日の言葉を残せ。",
    author: "人生の戒め",
    role: "ことわざ",
    category: "life",
  },
  {
    id: "w343",
    kind: "quote",
    text: "年齢は数字だ。好奇心が若さを保つ。",
    author: "パブロ・カザルス",
    role: "音楽家",
    category: "life",
  },
  {
    id: "w344",
    kind: "quote",
    text: "比較をやめれば、自分の道が見える。",
    author: "セオドア・ルーズベルト",
    role: "アメリカ大統領",
    category: "life",
  },
  {
    id: "w345",
    kind: "quote",
    text: "旅の目的地より、旅の仕方が人格をつくる。",
    author: "ゲーテ",
    role: "詩人",
    category: "life",
  },
  {
    id: "w346",
    kind: "quote",
    text: "十分なものは、多すぎるより美しい。",
    author: "老子",
    role: "思想家",
    category: "life",
  },
  {
    id: "w347",
    kind: "quote",
    text: "後悔は未来の燃料に変えよ。",
    author: "人生の知恵",
    role: "ことわざ",
    category: "life",
  },
  {
    id: "w348",
    kind: "quote",
    text: "静かな朝に、一日の調子は決まる。",
    author: "習慣の観察",
    role: "ことわざ",
    category: "life",
  },
  {
    id: "w349",
    kind: "quote",
    text: "生きるとは、何度でも始めることだ。",
    author: "サン＝テグジュペリ",
    role: "作家",
    category: "life",
  },
  {
    id: "w350",
    kind: "quote",
    text: "自分に正直であることは、他者への礼儀でもある。",
    author: "シェイクスピア",
    role: "劇作家",
    category: "life",
  },
  {
    id: "w351",
    kind: "quote",
    text: "時間を使うな。時間を生きよ。",
    author: "ヘンリー・デイヴィッド・ソロー",
    role: "思想家",
    category: "life",
  },
  {
    id: "w352",
    kind: "quote",
    text: "幸福は追うものではなく、気づくものだ。",
    author: "アリストテレス",
    role: "哲学者",
    category: "life",
  },
  {
    id: "w353",
    kind: "quote",
    text: "別れ際の優しさが、その人の本質を語る。",
    author: "人生の観察",
    role: "ことわざ",
    category: "life",
  },
  {
    id: "w354",
    kind: "quote",
    text: "今日できる親切を、明日に残すな。",
    author: "ウィリアム・ペン",
    role: "思想家",
    category: "life",
  },
  {
    id: "w355",
    kind: "quote",
    text: "人生は短い。だから丁寧に生きよ。",
    author: "セネカ",
    role: "哲学者",
    category: "life",
  },
  {
    id: "w356",
    kind: "quote",
    text: "持ち物を減らせ。心のスペースが増える。",
    author: "ミニマリズムの知恵",
    role: "ことわざ",
    category: "life",
  },
  {
    id: "w357",
    kind: "quote",
    text: "自然に触れよ。都市の喧騒は仮の現実だ。",
    author: "ジョン・ミューア",
    role: "自然保護",
    category: "life",
  },
  {
    id: "w358",
    kind: "quote",
    text: "老いは衰えではなく、視点の更新でもある。",
    author: "ユング",
    role: "心理学者",
    category: "life",
  },
  {
    id: "w359",
    kind: "quote",
    text: "愛は技術だ。才能だけで続かない。",
    author: "エーリッヒ・フロム",
    role: "心理学者",
    category: "life",
  },
  {
    id: "w360",
    kind: "quote",
    text: "一日を丁寧に生きることが、一生を丁寧に生きることだ。",
    author: "仏教の教え",
    role: "宗教",
    category: "life",
  },
  {
    id: "w361",
    kind: "quote",
    text: "失って初めてわかる価値がある。だから今、大切にせよ。",
    author: "人生の観察",
    role: "ことわざ",
    category: "life",
  },
  {
    id: "w362",
    kind: "quote",
    text: "自分のリズムを持て。他人の時計で走るな。",
    author: "ジャズの知恵",
    role: "音楽",
    category: "life",
  },
  {
    id: "w363",
    kind: "quote",
    text: "生き方は、毎日の小さな選択の総和だ。",
    author: "アリストテレス",
    role: "哲学者",
    category: "life",
  },
  {
    id: "w364",
    kind: "quote",
    text: "沈黙の時間は、浪費ではない。回復だ。",
    author: "パスカル",
    role: "哲学者",
    category: "life",
  },
  {
    id: "w365",
    kind: "quote",
    text: "美しい生き方は、派手さではなく一貫性にある。",
    author: "ストア派の教え",
    role: "哲学",
    category: "life",
  },
  {
    id: "w366",
    kind: "quote",
    text: "学ぶことをやめた者は、老いる。",
    author: "ヘンリー・フォード",
    role: "フォード創業者",
    category: "learning",
  },
  {
    id: "w367",
    kind: "quote",
    text: "本は、最も安く旅できる乗り物だ。",
    author: "エミリー・ディキンソン風",
    role: "作家",
    category: "learning",
  },
  {
    id: "w368",
    kind: "quote",
    text: "経験は最良の教師だが、授業料が高い。",
    author: "ベンジャミン・フランクリン",
    role: "政治家",
    category: "learning",
  },
  {
    id: "w369",
    kind: "quote",
    text: "質問は恥ではない。沈黙が学びを止める。",
    author: "孔子",
    role: "思想家",
    category: "learning",
  },
  {
    id: "w370",
    kind: "quote",
    text: "教えながら、自分がいちばん学ぶ。",
    author: "セネカ",
    role: "哲学者",
    category: "learning",
  },
  {
    id: "w371",
    kind: "quote",
    text: "基礎を侮るな。応用は基礎の上にしか建たない。",
    author: "武道の教え",
    role: "武道",
    category: "learning",
  },
  {
    id: "w372",
    kind: "quote",
    text: "好奇心は、学位より長く使える資格だ。",
    author: "アインシュタイン",
    role: "物理学者",
    category: "learning",
  },
  {
    id: "w373",
    kind: "quote",
    text: "間違いは、学習の領収書だ。",
    author: "教育の格言",
    role: "教育",
    category: "learning",
  },
  {
    id: "w374",
    kind: "quote",
    text: "読むだけで終わるな。書いて身につけよ。",
    author: "フランシス・ベーコン",
    role: "哲学者",
    category: "learning",
  },
  {
    id: "w375",
    kind: "quote",
    text: "学びの敵は、知ったかぶりだ。",
    author: "ソクラテス",
    role: "哲学者",
    category: "learning",
  },
  {
    id: "w376",
    kind: "quote",
    text: "毎日少しずつ。脳は積み上げに強い。",
    author: "習慣科学",
    role: "心理",
    category: "learning",
  },
  {
    id: "w377",
    kind: "quote",
    text: "師を持て。ただし盲従するな。",
    author: "仏教の教え",
    role: "宗教",
    category: "learning",
  },
  {
    id: "w378",
    kind: "quote",
    text: "学びは学校で終わらない。人生が教室だ。",
    author: "ジョン・デューイ",
    role: "教育哲学者",
    category: "learning",
  },
  {
    id: "w379",
    kind: "quote",
    text: "ノートは第二の脳だ。外部化せよ。",
    author: "知識管理の知恵",
    role: "知的生産",
    category: "learning",
  },
  {
    id: "w380",
    kind: "quote",
    text: "難しい本は、筋肉痛のようなものだ。あとで強くなる。",
    author: "読書のたとえ",
    role: "ことわざ",
    category: "learning",
  },
  {
    id: "w381",
    kind: "quote",
    text: "聞く力は、学ぶ力の入口だ。",
    author: "エピクロス",
    role: "哲学者",
    category: "learning",
  },
  {
    id: "w382",
    kind: "quote",
    text: "実践なき理論は空論、理論なき実践は迷走だ。",
    author: "カントの精神",
    role: "哲学",
    category: "learning",
  },
  {
    id: "w383",
    kind: "quote",
    text: "フィードバックを歓迎せよ。それは無料の教師だ。",
    author: "成長マインドセット",
    role: "心理",
    category: "learning",
  },
  {
    id: "w384",
    kind: "quote",
    text: "一つの専門を深め、隣接領域に橋を架けよ。",
    author: "レオナルド・ダ・ヴィンチ",
    role: "芸術家",
    category: "learning",
  },
  {
    id: "w385",
    kind: "quote",
    text: "忘却を恐れず、再学習を設計せよ。",
    author: "学習科学",
    role: "教育",
    category: "learning",
  },
  {
    id: "w386",
    kind: "quote",
    text: "子どもから学べ。新鮮な問いがある。",
    author: "モンテッソーリの精神",
    role: "教育",
    category: "learning",
  },
  {
    id: "w387",
    kind: "quote",
    text: "言語を学べ。世界の窓が増える。",
    author: "ゲーテ",
    role: "詩人",
    category: "learning",
  },
  {
    id: "w388",
    kind: "quote",
    text: "失敗のレビューが、次の成功の設計図だ。",
    author: "トヨタの改善",
    role: "製造業",
    category: "learning",
  },
  {
    id: "w389",
    kind: "quote",
    text: "学ぶ速度が、変化の速度に追いつかねばならない。",
    author: "ピーター・ドラッカー",
    role: "経営学者",
    category: "learning",
  },
  {
    id: "w390",
    kind: "quote",
    text: "暗記より理解、理解より応用を目指せ。",
    author: "学習の階層",
    role: "教育",
    category: "learning",
  },
  {
    id: "w391",
    kind: "quote",
    text: "対話は、独学の限界を超える。",
    author: "プラトン",
    role: "哲学者",
    category: "learning",
  },
  {
    id: "w392",
    kind: "quote",
    text: "学びを共有すると、自分の理解が深まる。",
    author: "教えることの効果",
    role: "教育",
    category: "learning",
  },
  {
    id: "w393",
    kind: "quote",
    text: "新しい技能は、最初の20時間がいちばん険しい。",
    author: "スキル習得の観察",
    role: "ことわざ",
    category: "learning",
  },
  {
    id: "w394",
    kind: "quote",
    text: "専門用語に逃げず、平易に説明できて初めて理解だ。",
    author: "ファインマン",
    role: "物理学者",
    category: "learning",
  },
  {
    id: "w395",
    kind: "quote",
    text: "歴史を学べ。同じ失敗を繰り返すな。",
    author: "シセロ",
    role: "政治家",
    category: "learning",
  },
  {
    id: "w396",
    kind: "quote",
    text: "観察眼を鍛えよ。教科書にない現実がある。",
    author: "ダーウィン",
    role: "生物学者",
    category: "learning",
  },
  {
    id: "w397",
    kind: "quote",
    text: "学びの習慣は、才能の格差を埋める。",
    author: "アンジェラ・ダックワース",
    role: "心理学者",
    category: "learning",
  },
  {
    id: "w398",
    kind: "quote",
    text: "今日の1ページが、一年後の景色を変える。",
    author: "読書習慣",
    role: "ことわざ",
    category: "learning",
  },
  {
    id: "w399",
    kind: "quote",
    text: "メタ認知——自分がどう学んでいるかを学べ。",
    author: "学習科学",
    role: "教育",
    category: "learning",
  },
  {
    id: "w400",
    kind: "quote",
    text: "異見に触れよ。同意の部屋では成長が遅い。",
    author: "ジョン・スチュアート・ミル",
    role: "哲学者",
    category: "learning",
  }
];

export function getWisdomById(id: string): Wisdom | undefined {
  return wisdoms.find((w) => w.id === id);
}

export function getWisdomsByCategory(slug: string): Wisdom[] {
  return wisdoms.filter((w) => w.category === slug);
}
