import type { Wisdom } from "./types";

/**
 * パブリックドメイン／広く知られた格言・逸話の日本語意訳・要約。
 * 原文の厳密な翻訳ではなく、読みやすさ優先の意訳を含む。
 */
export const wisdoms: Wisdom[] = [
  {
    id: "w001",
    kind: "quote",
    text: "人を動かす唯一の方法は、相手が自ら動きたいと思うようにすることだ。",
    author: "デール・カーネギー",
    role: "作家・教育者",
    category: "leadership",
  },
  {
    id: "w002",
    kind: "quote",
    text: "リーダーとは、道を示し、自ら歩き、そして人を信じて委ねる人である。",
    author: "ジャック・ウェルチ",
    role: "元GE CEO",
    category: "leadership",
  },
  {
    id: "w003",
    kind: "quote",
    text: "優れたリーダーは、部下の手柄を自分のものにしない。失敗は自分の責任として引き受ける。",
    author: "孫子",
    role: "兵法家",
    category: "leadership",
    source: "『孫子』の思想に基づく要約",
  },
  {
    id: "w004",
    kind: "quote",
    text: "マネジメントとは、正しいことを行うこと。リーダーシップとは、何が正しいかを決めることだ。",
    author: "ピーター・ドラッカー",
    role: "経営学者",
    category: "leadership",
  },
  {
    id: "w005",
    kind: "anecdote",
    text: "松下幸之助は、若い社員の提案を最後まで聞き、「あなたがそう言うなら、やってみよう」と答えたという。権限より信頼が、人を動かすと考えていた。",
    author: "松下幸之助",
    role: "パナソニック創業者",
    category: "leadership",
  },
  {
    id: "w006",
    kind: "quote",
    text: "イノベーションとは、顧客の言葉に従うことではない。顧客がまだ知らない欲求を見つけることだ。",
    author: "スティーブ・ジョブズ",
    role: "Apple共同創業者",
    category: "innovation",
  },
  {
    id: "w007",
    kind: "quote",
    text: "既存のものを少しよくするだけでは足りない。根本から作り直す覚悟が必要だ。",
    author: "イーロン・マスク",
    role: "起業家",
    category: "innovation",
  },
  {
    id: "w008",
    kind: "quote",
    text: "創造性とは、既存の要素を新しい組み合わせでつなぐことだ。",
    author: "アインシュタイン",
    role: "物理学者",
    category: "innovation",
  },
  {
    id: "w009",
    kind: "anecdote",
    text: "本田宗一郎は、失敗した試作車を前に怒らず、「失敗は成功の母だ。次をやれ」と技術者を励ましたという。挑戦を罰しない文化が、技術革新を支えた。",
    author: "本田宗一郎",
    role: "ホンダ創業者",
    category: "innovation",
  },
  {
    id: "w010",
    kind: "quote",
    text: "破壊的イノベーションは、最初は小さく、見過ごされやすい場所から始まる。",
    author: "クレイトン・クリステンセン",
    role: "経営学者",
    category: "innovation",
  },
  {
    id: "w011",
    kind: "quote",
    text: "天才とは、1%のひらめきと99%の努力である。",
    author: "トーマス・エジソン",
    role: "発明家",
    category: "perseverance",
  },
  {
    id: "w012",
    kind: "quote",
    text: "敗北は、あきらめたときにだけ確定する。",
    author: "孔子",
    role: "思想家",
    category: "perseverance",
  },
  {
    id: "w013",
    kind: "quote",
    text: "成功するまで続ければ、失敗ではない。",
    author: "ジョージ・パットン",
    role: "軍人",
    category: "perseverance",
  },
  {
    id: "w014",
    kind: "anecdote",
    text: "J.K.ローリングは、ハリー・ポッターの原稿を複数の出版社に断られた。それでも書き続け、世界的ベストセラーとなった。拒絶は終わりではなく、次の扉の前だった。",
    author: "J.K.ローリング",
    role: "作家",
    category: "perseverance",
  },
  {
    id: "w015",
    kind: "quote",
    text: "山は、登り続ける者の前にだけ道を開く。",
    author: "宮本武蔵",
    role: "剣豪",
    category: "perseverance",
    source: "『五輪書』の精神に基づく意訳",
  },
  {
    id: "w016",
    kind: "quote",
    text: "知ることは愛することの始まりであり、愛することは理解することの始まりである。",
    author: "ティッヒ・ナット・ハン",
    role: "僧侶・平和活動家",
    category: "wisdom",
  },
  {
    id: "w017",
    kind: "quote",
    text: "我思う、ゆえに我あり。",
    author: "デカルト",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w018",
    kind: "quote",
    text: "物事は、あなたがどう見るかによって変わる。見方を変えれば、世界も変わる。",
    author: "マルクス・アウレリウス",
    role: "ローマ皇帝・ストア派哲学者",
    category: "wisdom",
  },
  {
    id: "w019",
    kind: "quote",
    text: "無知の知——自分が知らないことを知る者こそ、賢い。",
    author: "ソクラテス",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w020",
    kind: "anecdote",
    text: "老子は、強さとは水のように柔らかいものだと説いた。岩を削るのも、低い場所へ流れるのも、争わずに道を見つけるのも水である、と。",
    author: "老子",
    role: "思想家",
    category: "wisdom",
  },
  {
    id: "w021",
    kind: "quote",
    text: "企業の目的は、顧客の創造である。",
    author: "ピーター・ドラッカー",
    role: "経営学者",
    category: "business",
  },
  {
    id: "w022",
    kind: "quote",
    text: "価格は忘れられても、品質は長く残る。",
    author: "グルーチョ・マルクス（通説）／品質経営の格言",
    role: "経営の諺",
    category: "business",
  },
  {
    id: "w023",
    kind: "quote",
    text: "あなたの利益は、顧客が払う対価ではなく、顧客が得る価値にある。",
    author: "ジェフ・ベゾス",
    role: "Amazon創業者",
    category: "business",
  },
  {
    id: "w024",
    kind: "anecdote",
    text: "稲盛和夫は、京セラ創業時から「値決めは経営である」と説いた。安売りでも暴利でもなく、お客様も会社も納得できる一点を見つけることが、経営者の仕事だと。",
    author: "稲盛和夫",
    role: "京セラ創業者",
    category: "business",
  },
  {
    id: "w025",
    kind: "quote",
    text: "小さく始め、早く学び、大きく育てよ。",
    author: "エリック・リース",
    role: "起業家・著者",
    category: "business",
  },
  {
    id: "w026",
    kind: "quote",
    text: "勇気とは、恐れがないことではない。恐れがあっても前へ進むことだ。",
    author: "ネルソン・マンデラ",
    role: "政治家・人権活動家",
    category: "courage",
  },
  {
    id: "w027",
    kind: "quote",
    text: "船は港にいれば安全だ。だが、それは船の目的ではない。",
    author: "ジョン・A・シェッド",
    role: "著述家",
    category: "courage",
  },
  {
    id: "w028",
    kind: "quote",
    text: "人生で最も大きな危険は、危険を冒さないことだ。",
    author: "マーク・ザッカーバーグ",
    role: "Meta創業者",
    category: "courage",
  },
  {
    id: "w029",
    kind: "anecdote",
    text: "ヘレン・ケラーは視覚と聴覚を失いながらも、世界に向けて語り続けた。「世界で最も美しいものは、目で見たり触れたりできない。心で感じなければならない」と。",
    author: "ヘレン・ケラー",
    role: "著述家・社会活動家",
    category: "courage",
  },
  {
    id: "w030",
    kind: "quote",
    text: "困難の中に、機会がある。",
    author: "アインシュタイン",
    role: "物理学者",
    category: "courage",
  },
  {
    id: "w031",
    kind: "quote",
    text: "人生とは、自分が他の人のために何をしたかで測られる。",
    author: "アインシュタイン",
    role: "物理学者",
    category: "life",
  },
  {
    id: "w032",
    kind: "quote",
    text: "今日という日は、残りの人生の最初の日である。",
    author: "チャールズ・ディケンズ（通説）",
    role: "作家",
    category: "life",
  },
  {
    id: "w033",
    kind: "quote",
    text: "シンプルに生きよ。ただし、単純には考えるな。",
    author: "オリバー・ウェンデル・ホームズ",
    role: "法学者",
    category: "life",
  },
  {
    id: "w034",
    kind: "anecdote",
    text: "ガンディーは、簡素な生活と非暴力を貫いた。力でねじ伏せるのではなく、正しさで相手の良心に訴える——それが、彼の選んだ生き方だった。",
    author: "マハトマ・ガンディー",
    role: "独立運動指導者",
    category: "life",
  },
  {
    id: "w035",
    kind: "quote",
    text: "幸せは、向かう方向であって、場所ではない。",
    author: "シドニー・J・ハリス",
    role: "ジャーナリスト",
    category: "life",
  },
  {
    id: "w036",
    kind: "quote",
    text: "学びて思わざれば則ち罔し。思いて学ばざれば則ち殆し。",
    author: "孔子",
    role: "思想家",
    category: "learning",
    source: "『論語』",
  },
  {
    id: "w037",
    kind: "quote",
    text: "私は特別に才能があるわけではない。ただ、情熱的に好奇心を持つだけだ。",
    author: "アインシュタイン",
    role: "物理学者",
    category: "learning",
  },
  {
    id: "w038",
    kind: "quote",
    text: "読書は、すでに考えられたことを追体験する最も速い方法だ。",
    author: "チャーリー・マンガー",
    role: "投資家",
    category: "learning",
  },
  {
    id: "w039",
    kind: "anecdote",
    text: "福沢諭吉は、蘭学から英語へ、そして西洋の制度へと学び続けた。一つの知識に安住せず、時代が求める次の学びへ移る姿勢が、近代日本の精神を形づくった。",
    author: "福沢諭吉",
    role: "思想家・教育者",
    category: "learning",
  },
  {
    id: "w040",
    kind: "quote",
    text: "経験から学ぶ者は賢い。他人の経験から学ぶ者は、さらに賢い。",
    author: "オットー・フォン・ビスマルク",
    role: "政治家",
    category: "learning",
  },
  {
    id: "w041",
    kind: "quote",
    text: "ビジョンなきところに、実行も成果もない。",
    author: "ヘレン・ケラー",
    role: "著述家・社会活動家",
    category: "leadership",
  },
  {
    id: "w042",
    kind: "quote",
    text: "最も重要なことは、言うことではなく、行うことだ。",
    author: "ジョン・ウッドン",
    role: "バスケットボール指導者",
    category: "leadership",
  },
  {
    id: "w043",
    kind: "quote",
    text: "変化を恐れず、変化を自ら起こす側に回れ。",
    author: "ジャック・マー",
    role: "アリババ創業者",
    category: "innovation",
  },
  {
    id: "w044",
    kind: "quote",
    text: "最初から完璧を目指すな。まず動け。",
    author: "リード・ホフマン",
    role: "LinkedIn共同創業者",
    category: "innovation",
  },
  {
    id: "w045",
    kind: "quote",
    text: "落下しても、立ち上がる回数の方が多ければよい。",
    author: "孔子",
    role: "思想家",
    category: "perseverance",
  },
  {
    id: "w046",
    kind: "quote",
    text: "石の上にも三年。ただし、三年で諦めるな。十年を見据えよ。",
    author: "日本の諺（拡張）",
    role: "ことわざ",
    category: "perseverance",
  },
  {
    id: "w047",
    kind: "quote",
    text: "静かな心は、どんな嵐の中でも港になれる。",
    author: "エピクロス",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w048",
    kind: "quote",
    text: "測れるものは改善できる。測れないものは管理できない。",
    author: "ピーター・ドラッカー",
    role: "経営学者",
    category: "business",
  },
  {
    id: "w049",
    kind: "quote",
    text: "顧客に恋をし、競合に執着するな。",
    author: "ジェフ・ベゾス",
    role: "Amazon創業者",
    category: "business",
  },
  {
    id: "w050",
    kind: "quote",
    text: "安全な道を選ぶことが、いちばん危険なときがある。",
    author: "パウロ・コエーリョ",
    role: "作家",
    category: "courage",
  },
  {
    id: "w051",
    kind: "quote",
    text: "人生の意味は、与えられるものではなく、自らつくるものだ。",
    author: "ヴィクトール・フランクル",
    role: "精神科医・著者",
    category: "life",
  },
  {
    id: "w052",
    kind: "quote",
    text: "教育の目的は、知識を詰めることではなく、考える力を育てることだ。",
    author: "アインシュタイン",
    role: "物理学者",
    category: "learning",
  },
  {
    id: "w053",
    kind: "quote",
    text: "信頼は、言葉ではなく一貫した行動から生まれる。",
    author: "スティーブン・R・コヴィー",
    role: "著述家",
    category: "leadership",
  },
  {
    id: "w054",
    kind: "anecdote",
    text: "渋沢栄一は、利益と道徳は両立すると説き、『論語と算盤』にその思想を残した。事業の成功は、社会への貢献と切り離せない、というのが彼の経営観だった。",
    author: "渋沢栄一",
    role: "実業家",
    category: "business",
  },
  {
    id: "w055",
    kind: "quote",
    text: "アイデアは安い。実行がすべてだ。",
    author: "スティーブ・ジョブズ",
    role: "Apple共同創業者",
    category: "innovation",
  },
  {
    id: "w056",
    kind: "quote",
    text: "忍耐とは、待っているあいだに何をするかだ。",
    author: "ヘンリー・ロングフェロー",
    role: "詩人",
    category: "perseverance",
  },
  {
    id: "w057",
    kind: "quote",
    text: "自分を知ることは、すべての知恵の始まりである。",
    author: "アリストテレス",
    role: "哲学者",
    category: "wisdom",
  },
  {
    id: "w058",
    kind: "quote",
    text: "恐れは心の中にある。踏み出せば、恐れの半分は消える。",
    author: "セオドア・ルーズベルト",
    role: "アメリカ大統領",
    category: "courage",
  },
  {
    id: "w059",
    kind: "quote",
    text: "人生は短い。だからこそ、大切なことに時間を使え。",
    author: "セネカ",
    role: "哲学者",
    category: "life",
  },
  {
    id: "w060",
    kind: "quote",
    text: "学び続ける者だけが、変化する世界についていける。",
    author: "ピーター・ドラッカー",
    role: "経営学者",
    category: "learning",
  },
  {
    id: "w061",
    kind: "quote",
    text: "人を雇うときは、スキルより意志を見よ。スキルは教えられる。",
    author: "サイモン・シネック",
    role: "著述家",
    category: "leadership",
  },
  {
    id: "w062",
    kind: "quote",
    text: "明日の当たり前は、今日の非常識から生まれる。",
    author: "孫正義",
    role: "ソフトバンクグループ創業者",
    category: "innovation",
  },
  {
    id: "w063",
    kind: "anecdote",
    text: "ウォルト・ディズニーは破産を経験し、ミッキーマウスの構想も当初は相手にされなかった。それでも物語と夢を諦めず、やがて娯楽の帝国をつくった。",
    author: "ウォルト・ディズニー",
    role: "起業家・アニメーター",
    category: "perseverance",
  },
  {
    id: "w064",
    kind: "quote",
    text: "真実は、わかりやすい言葉の中にあることが多い。",
    author: "レオナルド・ダ・ヴィンチ",
    role: "芸術家・発明家",
    category: "wisdom",
  },
  {
    id: "w065",
    kind: "quote",
    text: "長期で考え、短期で実行せよ。",
    author: "ジェフ・ベゾス",
    role: "Amazon創業者",
    category: "business",
  },
  {
    id: "w066",
    kind: "quote",
    text: "勇気の反対は臆病ではない。適合することだ。",
    author: "ロロ・メイ",
    role: "心理学者",
    category: "courage",
  },
  {
    id: "w067",
    kind: "quote",
    text: "自分の人生の著者になれ。他人の脚注になるな。",
    author: "オリバー・ウェンデル・ホームズ",
    role: "法学者",
    category: "life",
  },
  {
    id: "w068",
    kind: "quote",
    text: "質問を変えると、見える世界が変わる。",
    author: "アインシュタイン",
    role: "物理学者",
    category: "learning",
  },
  {
    id: "w069",
    kind: "quote",
    text: "部下に仕事を任せるとは、結果を任せる覚悟を持つことだ。",
    author: "松下幸之助",
    role: "パナソニック創業者",
    category: "leadership",
  },
  {
    id: "w070",
    kind: "quote",
    text: "技術は手段だ。目的は、人の生活をよりよくすることにある。",
    author: "ビル・ゲイツ",
    role: "Microsoft共同創業者",
    category: "innovation",
  },
  {
    id: "w071",
    kind: "quote",
    text: "継続は力なり。ただし、改善なき継続は惰性なり。",
    author: "日本の諺（拡張）",
    role: "ことわざ",
    category: "perseverance",
  },
  {
    id: "w072",
    kind: "quote",
    text: "怒りは一時の狂気である。",
    author: "ホラティウス",
    role: "詩人",
    category: "wisdom",
  },
  {
    id: "w073",
    kind: "anecdote",
    text: "盛田昭夫は、ウォークマンの社内反対を押し切り発売した。市場調査に頼るより、「人々が音楽を持ち歩く世界」を信じた決断だった。",
    author: "盛田昭夫",
    role: "ソニー共同創業者",
    category: "business",
  },
  {
    id: "w074",
    kind: "quote",
    text: "最初の一歩が、いちばん勇気がいる。",
    author: "老子",
    role: "思想家",
    category: "courage",
  },
  {
    id: "w075",
    kind: "quote",
    text: "比較は、喜びを盗む泥棒だ。",
    author: "セオドア・ルーズベルト",
    role: "アメリカ大統領",
    category: "life",
  },
  {
    id: "w076",
    kind: "quote",
    text: "教えることは、二度学ぶことだ。",
    author: "ジョセフ・ジュベール",
    role: "随筆家",
    category: "learning",
  },
  {
    id: "w077",
    kind: "quote",
    text: "文化は戦略に勝る。どんな計画も、現場の空気に負ける。",
    author: "ピーター・ドラッカー",
    role: "経営学者",
    category: "leadership",
  },
  {
    id: "w078",
    kind: "quote",
    text: "未来は、予測するものではなく、つくるものだ。",
    author: "ピーター・ドラッカー",
    role: "経営学者",
    category: "innovation",
  },
  {
    id: "w079",
    kind: "quote",
    text: "成功の反対は失敗ではない。何もしないことだ。",
    author: "ロバート・シューラー",
    role: "牧師・著述家",
    category: "perseverance",
  },
  {
    id: "w080",
    kind: "quote",
    text: "知恵とは、何を無視すべきかを知ることだ。",
    author: "ウィリアム・ジェームズ",
    role: "心理学者・哲学者",
    category: "wisdom",
  },
];

export function getWisdomById(id: string): Wisdom | undefined {
  return wisdoms.find((w) => w.id === id);
}

export function getWisdomsByCategory(slug: string): Wisdom[] {
  return wisdoms.filter((w) => w.category === slug);
}
